### PR TITLE
Some UI improvements

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by wtrocki** [comment]
@danielpassos Awesome work! Quickly glanced. This PR is critical to get into master.
I will review this as soon as possible and rebase offline support from my branch.

**Comment by wtrocki** [comment]
There are couple things that do not work, but are totally unrelated to this PR.
I would like to work on this and fix it, but since problems are related with server side and are already on master we should merge that and look to improve stuff as part of the other work.

**Comment by danielpassos** [comment]
@wtrocki Let me know if I broke something and what I can do to help to fix it.

**Comment by wtrocki** [comment]
We need to redesign example schema on server first and then change frontend to use cache first

**Comment by wtrocki** [comment]
Nothing broken in your changes

**Pull request merged**
