### PR TITLE
fix: subscriptions endpoint in mobile-services.json

### PR DESCRIPTION
**Pull request by darahayes**
I know this file is only an example file, but it makes sense that it doesn't convey any incorrect information.

### CODE REVIEW

**Comment by wtrocki** [comment]
@darahayes Migrated to new backend 2.0, changed this, but then started to think that we do not need separate URL for subscriptions. Do you personally see any reason to let people use different URL's for those?
Obviously this PR is pure gold - thank you for fixing that, but asking more top level question

**Comment by darahayes** [comment]
@wtrocki great question. I would actually rather go with the approach you mention, however, I was worried about what would happen if it changes again. If we go with the approach you mention there will be some small change needed for in the Sync SDK to initialise the subscriptions client properly.

**Comment by darahayes** [comment]
@wtrocki Happy to go with this approach though as it would mean no additional changes to the APB.

**Comment by darahayes** [comment]
@wtrocki I have updated it to use just one url. Can we get this updated in the relevant SDKs?

**Pull request merged**
