### PR TITLE
fix: check for errors in likeMeme request

### PR DESCRIPTION
**Pull request by darahayes**

### CODE REVIEW

**Comment by wtrocki** [comment]
ping @wojta @psturc Same aproach will need to be taken on IOS.

**Comment by wtrocki** [comment]
It's good for like meme but we should probably do that for all requests we do. Created separate low hanging ticket: https://issues.jboss.org/browse/AEROGEAR-7832

**Comment by danielpassos** [comment]
@wtrocki This is a scenario where the wrapper is a good one.

**Comment by wtrocki** [comment]
@danielpassos you have taken that from my mind! 
Perfect scenario for wrapper! I have took the ticket for getting things into wrapper.

**Comment by danielpassos** [comment]
@wtrocki I'm working on adding this to the already existent wrapper methods.

**Pull request merged**
