### PR TITLE
Add security on memeolist

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by wtrocki** [comment]
Process: org.aerogear.android.app.memeolist, PID: 9892
                                                                                  android.content.res.Resources$NotFoundException: Array resource ID #0x7f030003

**Comment by wtrocki** [comment]
@danielpassos After dropping 2 last commits application works but... Still crashes after login.

**Comment by danielpassos** [comment]
@wtrocki My bad, I have changed the `UserProfile` is for the Keycloak Username but it's not an int and for some reason, the callback never called `onFailure`

**Comment by wtrocki** [comment]
@danielpassos Thanks for login screen. It will be cool to add some logo picture later stage in separate PR.

**Comment by danielpassos** [comment]
@wtrocki I will work on that **OR** kill the login screen ;)

**Pull request merged**
