### PR TITLE
Memeolist logout

### PR DESCRIPTION
**Pull request by danielpassos**
I have implemented a logout on the memeolist app, but from time to time we are losing the currentUser reference raising an NPE on logout.

### CODE REVIEW

**Comment by wtrocki** [comment]
Activities have wrong launch mode configuration. Going back after login is dropping main activity and go back to login. This should not be possible. Main Activity (MemeList) should be the single activity in history. 
It will be better to stack login on top of the main activity and remove it from history.

It is also possible to press back on login screen and go back to the main screen. Previously logged user data is being used, but single user is not authenticated in the backend all requests failing. However with cache enabled data will be shown. 

I would love to verify that again after we merge changes from core SDK related to authentication

**Comment by psturc** [comment]
Just addition to Wojtek's review: after logout and going back, everything on the main screen still worked for me - refresh, creating memes, likes, comments. After hitting logout button again, the app has stopped.
Tested on Android simulator Pixel API 25.

**Comment by danielpassos** [comment]
@wtrocki @psturc Fixed!

**Comment by psturc** [comment]
👀

**Comment by wtrocki** [comment]
@danielpassos Hi. After login I can still go back to login screen, but this time login is disabled.

**Comment by danielpassos** [comment]
@wtrocki LoginActivity is responsible to [handle](https://github.com/danielpassos/aerogear-android-example-apps/blob/memeolist-logout/memeolist/app/src/main/java/org/aerogear/android/app/memeolist/ui/LoginActivity.java#L35-L40) the Keycloak callback. After that, you should be [redirected](https://github.com/danielpassos/aerogear-android-example-apps/blob/memeolist-logout/memeolist/app/src/main/java/org/aerogear/android/app/memeolist/ui/LoginActivity.java#L53) to the MemeListActivity. Is this not happening?

**Comment by wtrocki** [comment]
I actually got problem with update. I think that emulator was still using the old version despite compilation finishing fine. It works now.

**Comment by danielpassos** [comment]
@wtrocki Question: Should we kill the login screen and do all the process in the list screen?

**Comment by danielpassos** [comment]
@wtrocki I will improve the login screen soo-ish. Just wanna ship the log out to unblock you.

**Comment by wtrocki** [comment]
@danielpassos Login screen was coming form the idea of application welcome screen initially. I would not invest much into it or removing it completely.

**Comment by danielpassos** [comment]
@psturc It's for now, but we are revisiting it.

**Pull request merged**
